name: Vanillie
version: 1.6
main: com.vunilly.vanillie.Vanillie
api-version: '26.1'

commands:
  tag:
    description: Lets you add tags to your username
    aliases: [prefix]
    usage: /tag
  pvp:
    description: Lets you toggle pvp
    aliases: []
    usage: /pvp
  vote:
    description: Lets you vote for clear weather or time
    aliases: []
    usage: /vote
  size:
    description: Change your ingame size
    aliases: []
    usage: /size
  twitch:
    description: Lets you connect your Twitch channel and show a notification when you are live
    aliases: [ttv, stream]
    usage: /twitch
  color:
    description: Lets you change your name color
    aliases: [namecolor, color]
  vanillieconf:
    description: Manage config files
    aliases: [vconf]
    usage: /vanillie <reloadconfig|saveconfig|clearconfig>
  vanillie:
    description: Plugin Info
    aliases: [vinfo, v]
    usage: /vanillieinfo
  vanilliesettings:
    description: Plugin Settings
    aliases: [vpref, vsettings]
    usage: /vanilliesettings
  schedulerestart:
    description: Manage restarting your server
    aliases: [vrestart]
    usage: /schedulerestart