name: Vanillie
version: 1.0
main: com.vunilly.vanillie.Vanillie
api-version: '26.1'

commands:
  tag:
    description: Lets you add tags to your username
    aliases: [prefix]
    usage: /tag
  vanillieconfig:
    description: Configuration commands
    aliases: [vconfig, vconf]
    usage: /vanillieconfig <reload|save>