name: Vanillie
version: 1.7
main: com.vunilly.vanillie.Vanillie
api-version: '26.2'

commands:
  tag:
    description: Lets you add tags to your username
    aliases: [prefix]
    usage: /tag
  pvp:
    description: Lets you toggle pvp
    aliases: []
    usage: /pvp
  vote:
    description: Lets you vote for clear weather or time
    aliases: []
    usage: /vote
  size:
    description: Change your ingame size
    aliases: []
    usage: /size
  twitch:
    description: Lets you connect your Twitch channel and show a notification when you are live
    aliases: [ttv, stream]
    usage: /twitch
  stats:
    description: Get Stats of players
    aliases: [ info ]
    usage: /stats <enderchest|inventory|playtime> <name>
  givebiomewand:
    description: Gives you the Biomewand
    aliases: []
    usage: /givebiomewand
  vanillieconf:
    description: Plugin config command
    aliases: [vconf]
    usage: /vanillieconf <reloadconfig|saveconfig|clearconfig>
  vanillie:
    description: Plugin Info
    aliases: [vinfo, v]
    usage: /vanillieinfo
  vanilliesettings:
    description: Plugin Settings
    aliases: [vpref, vsettings]
    usage: /vanilliesettings
  schedulerestart:
    description: Manage restarting your server
    aliases: [vrestart]
    usage: /schedulerestart